# Use a lightweight Nginx image
FROM nginx:1.25-alpine

# Remove the default Nginx welcome page
RUN rm /usr/share/nginx/html/*

# Copy the static frontend files to the Nginx html directory
COPY ./dashboard/ /usr/share/nginx/html/

# Expose port 80 for Nginx
EXPOSE 80

# The default Nginx command will start the server
CMD ["nginx", "-g", "daemon off;"]
