FROM python:3.9-slim

WORKDIR /app

# Install Python dependencies
RUN pip install --no-cache-dir \
  kafka-python==2.0.2 \
  pandas==2.1.4

# Copy producer scripts and datasets into the image
COPY ./producer-scripts/ /app/
COPY ./datasets/ /app/datasets/

# Run the correct producer script
CMD ["python", "ecommerce_producer.py"]